CREATE DATABASE BARBEARIA;
USE BARBEARIA;

CREATE TABLE clientes (
    id_Cliente INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    telefone VARCHAR(15) NOT NULL
);